[Appearance]
color_scheme_path=/home/noblixy/.config/qt6ct/colors/rice.conf
custom_palette=true
icon_theme=breeze-dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="FiraCode Nerd Font,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
activate_item_on_single_click=0
dialog_buttons_have_icons=1
menus_have_icons=true
show_shortcuts_in_context_menus=true
underline_shortcut=1
wheel_scroll_lines=3
